# HTTP Server
server:
  port: ${PORT:8080}   # HTTP port
  
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.atsistemas: 'DEBUG'

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ENDPOINT}
          
#Spring properties 
spring:  
  aop:
    auto: true
    proxy-target-class: false
  messages:
    always-use-message-format: false
    basename: messages
    cache-seconds: -1
  mvc:
    async:
      request-timeout: 300
    date-format: DD/MM/YYYY
    favicon:
      enabled: true
    dispatch-options-request: true
    dispatch-trace-request: false
  couchbase:
    bucket:
      name: default
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 
  datasource:
    url: jdbc:mysql://localhost:3306/dminute?useSSL=false
    username: root
    password: 123456      
#Security properties      
security: 
  oauth2:
    resource:
      service-id: resource
      prefer-token-info: true   
 